[zookeeper]
enabled=false

[cluster.local]
class-name="kafka"
servers=[ "kfk-node1.staging.fun-box.ru:9092" ]
topic-refresh=60
offset-refresh=30
groups-reaper-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "kfk-node1.staging.fun-box.ru:9092" ]
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[httpserver.default]
address=":8000"
